# Generated by Django 2.2.5 on 2019-09-10 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190910_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 10, 16, 29, 8, 804910)),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='timeInitiated',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 10, 16, 29, 8, 804427)),
        ),
    ]
