# Generated by Django 2.2.4 on 2019-09-11 19:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190910_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wbs_item',
            name='cc_index',
        ),
        migrations.RemoveField(
            model_name='wbs_item',
            name='name',
        ),
        migrations.AddField(
            model_name='wbs_item',
            name='cc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.CostCenters'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 11, 19, 49, 19, 953194)),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='timeInitiated',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 11, 19, 49, 19, 952716)),
        ),
    ]
