# Generated by Django 2.2.4 on 2019-09-11 19:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190911_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='WBS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Budget')),
                ('cc', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.CostCenters')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 11, 19, 52, 13, 844947)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='wbs_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.WBS'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='timeInitiated',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 11, 19, 52, 13, 844458)),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_target',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_target', to='dashboard.WBS'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='wbs_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wbs_item', to='dashboard.WBS'),
        ),
        migrations.DeleteModel(
            name='WBS_Item',
        ),
    ]
