# Generated by Django 2.2.4 on 2019-09-12 10:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190911_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('timeInitiated', models.DateTimeField(default=datetime.datetime(2019, 9, 12, 10, 30, 35, 982766))),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.BooleanField(default=True)),
                ('wbs_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.WBS')),
            ],
        ),
        migrations.CreateModel(
            name='TypeThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Trans')),
                ('transfer_target', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.WBS')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 12, 10, 30, 35, 983525)),
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
