# Generated by Django 2.2.4 on 2019-09-12 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190912_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 12, 19, 37, 36, 632950)),
        ),
        migrations.AlterField(
            model_name='trans',
            name='timeInitiated',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 12, 19, 37, 36, 632163)),
        ),
    ]
