# Generated by Django 2.2.4 on 2019-09-12 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190912_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 12, 20, 27, 2, 631212)),
        ),
        migrations.AlterField(
            model_name='trans',
            name='timeInitiated',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 12, 20, 27, 2, 630425)),
        ),
    ]
